<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [1]:
!pip install pandas
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\hasgh\appdata\roaming\python\python310\site-packages (2.3.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from pandas) (2025.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip available: 22.2.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\hasgh\appdata\roaming\python\python310\site-packages (3.10.8)
Requirement already satisfied: packaging>=20.0 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from matplotlib) (25.0)
Requirement already satisfied: numpy>=1.23 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from matplotlib) (2.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from matplotlib) (3.3.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: six>=1.5 in c:\users\hasgh\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip available: 22.2.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [2]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
print(df.head())

   ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old
1           2  I am a developer by profession     35-44 years old
2           3  I am a developer by profession     45-54 years old
3           4           I am learning to code     18-24 years old
4           5  I am a developer by profession     18-24 years old

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples
1  Employed, full-time     Remote  Apples
2  Employed, full-time     Remote  Apples
3   Student, full-time        NaN  Apples
4   Student, full-time        NaN  Apples

                                    CodingActivities  \
0                                              Hobby
1  Hobby;Contribute to open-source projects;Other...
2  Hobby;Contribute to open-source projects;Other...
3                                                NaN
4                                                NaN

                                             EdLevel  \
0                          Primary/elementary school
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3  Some college/university study without earning ...
4  Secondary school (e.g. American high school, G...

                                           LearnCode  \
0                             Books / Physical media
1  Books / Physical media;Colleague;On the job tr...
2  Books / Physical media;Colleague;On the job tr...
3  Other online resources (e.g., videos, blogs, f...
4  Other online resources (e.g., videos, blogs, f...

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN
1            0.0            0.0            0.0             0.0
2            NaN            NaN            NaN             NaN
3            NaN            NaN            NaN             NaN
4            NaN            NaN            NaN             NaN

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat
0             NaN                    NaN        NaN                 NaN    NaN
1             0.0                    NaN        NaN                 NaN    NaN
2             NaN  Appropriate in length       Easy                 NaN    NaN
3             NaN               Too long       Easy                 NaN    NaN
4             NaN              Too short       Easy                 NaN    NaN

[5 rows x 114 columns]

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65437 entries, 0 to 65436
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 56.9+ MB

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [4]:
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [5]:
df['Country'].value_counts()

Country
United States of America                                11095
Germany                                                  4947
India                                                    4231
United Kingdom of Great Britain and Northern Ireland     3224
Ukraine                                                  2672
                                                        ...
Micronesia, Federated States of...                          1
Nauru                                                       1
Chad                                                        1
Djibouti                                                    1
Solomon Islands                                             1
Name: count, Length: 185, dtype: int64

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [6]:
df['Country'] = df['Country'].replace({
    'United States of America':'USA',
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom'
})

In [7]:
df['Country'].value_counts()

Country
USA                                   11095
Germany                                4947
India                                  4231
United Kingdom                         3224
Ukraine                                2672
                                      ...
Micronesia, Federated States of...        1
Nauru                                     1
Chad                                      1
Djibouti                                  1
Solomon Islands                           1
Name: count, Length: 185, dtype: int64

In [8]:
df['Country'].unique()

array(['USA', 'United Kingdom', 'Canada', 'Norway', 'Uzbekistan',
       'Serbia', 'Poland', 'Philippines', 'Bulgaria', 'Switzerland',
       'India', 'Germany', 'Ireland', 'Italy', 'Ukraine', 'Australia',
       'Brazil', 'Japan', 'Austria', 'Iran, Islamic Republic of...',
       'France', 'Saudi Arabia', 'Romania', 'Turkey', 'Nepal', 'Algeria',
       'Sweden', 'Netherlands', 'Croatia', 'Pakistan', 'Czech Republic',
       'Republic of North Macedonia', 'Finland', 'Slovakia',
       'Russian Federation', 'Greece', 'Israel', 'Belgium', 'Mexico',
       'United Republic of Tanzania', 'Hungary', 'Argentina', 'Portugal',
       'Sri Lanka', 'Latvia', 'China', 'Singapore', 'Lebanon', 'Spain',
       'South Africa', 'Lithuania', 'Viet Nam', 'Dominican Republic',
       'Indonesia', 'Kosovo', 'Morocco', 'Taiwan', 'Georgia',
       'San Marino', 'Tunisia', 'Bangladesh', 'Nigeria', 'Liechtenstein',
       'Denmark', 'Ecuador', 'Malaysia', 'Albania', 'Azerbaijan', 'Chile',
       'Ghana', 'Peru', 'Bolivia', 'Egypt', 'Luxembourg', 'Montenegro',
       'Cyprus', 'Paraguay', 'Kazakhstan', 'Slovenia', 'Jordan',
       'Venezuela, Bolivarian Republic of...', 'Costa Rica', 'Jamaica',
       'Thailand', 'Nicaragua', 'Myanmar', 'Republic of Korea', 'Rwanda',
       'Bosnia and Herzegovina', 'Benin', 'El Salvador', 'Zimbabwe',
       'Afghanistan', 'Estonia', 'Malta', 'Uruguay', 'Belarus',
       'Colombia', 'Republic of Moldova', 'Isle of Man', 'Nomadic',
       'New Zealand', 'Palestine', 'Armenia', 'United Arab Emirates',
       'Maldives', 'Ethiopia', 'Fiji', 'Guatemala', 'Uganda',
       'Turkmenistan', 'Mauritius', 'Kenya', 'Cuba', 'Gabon', 'Bahamas',
       'South Korea', 'Iceland', 'Honduras', 'Hong Kong (S.A.R.)',
       "Lao People's Democratic Republic", 'Mongolia', 'Cambodia',
       'Madagascar', 'Angola', 'Democratic Republic of the Congo',
       'Syrian Arab Republic', 'Iraq', 'Namibia', 'Senegal', 'Kyrgyzstan',
       'Zambia', 'Swaziland', "Côte d'Ivoire", 'Kuwait', 'Tajikistan',
       'Burundi', 'Trinidad and Tobago', 'Mauritania', 'Sierra Leone',
       'Panama', 'Somalia', 'North Korea', 'Dominica', 'Guyana', 'Togo',
       'Oman', 'Barbados', 'Andorra',
       "Democratic People's Republic of Korea", 'Qatar', 'Sudan',
       'Cameroon', 'Papua New Guinea', 'Bahrain', 'Yemen', 'Malawi',
       'Burkina Faso', 'Congo, Republic of the...', 'Botswana',
       'Guinea-Bissau', 'Mozambique', 'Central African Republic',
       'Equatorial Guinea', 'Suriname', 'Belize',
       'Libyan Arab Jamahiriya', 'Cape Verde', 'Brunei Darussalam',
       'Bhutan', 'Guinea', 'Niger', 'Antigua and Barbuda', 'Mali',
       'Samoa', 'Lesotho', 'Saint Kitts and Nevis', 'Monaco',
       'Micronesia, Federated States of...', 'Haiti', nan, 'Nauru',
       'Liberia', 'Chad', 'Djibouti', 'Solomon Islands'], dtype=object)

In [9]:
df['Country'].value_counts().sort_index(key=lambda x: x.str.len(), ascending=False).head(20)

Country
Democratic People's Republic of Korea      2
Venezuela, Bolivarian Republic of...      69
Micronesia, Federated States of...         1
Lao People's Democratic Republic           4
Democratic Republic of the Congo           3
Iran, Islamic Republic of...             411
Republic of North Macedonia               36
United Republic of Tanzania               28
Congo, Republic of the...                  8
Central African Republic                   1
Libyan Arab Jamahiriya                     4
Bosnia and Herzegovina                    62
Saint Kitts and Nevis                      1
Syrian Arab Republic                      30
United Arab Emirates                     130
Antigua and Barbuda                        5
Republic of Moldova                       38
Trinidad and Tobago                        8
Hong Kong (S.A.R.)                       146
Dominican Republic                        47
Name: count, dtype: int64

In [10]:
df['Country'].value_counts().head()

Country
USA               11095
Germany            4947
India              4231
United Kingdom     3224
Ukraine            2672
Name: count, dtype: int64

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [12]:
df['Employment'].value_counts()

Employment
Employed, full-time                                                                                                                                   39041
Independent contractor, freelancer, or self-employed                                                                                                   4846
Student, full-time                                                                                                                                     4709
Employed, full-time;Independent contractor, freelancer, or self-employed                                                                               3557
Not employed, but looking for work                                                                                                                     2341
                                                                                                                                                      ...
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time        1
Student, full-time;Retired                                                                                                                                1
Employed, full-time;Not employed, but looking for work;Student, part-time                                                                                 1
Not employed, and not looking for work;Student, part-time;Employed, part-time                                                                             1
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Retired                                        1
Name: count, Length: 110, dtype: int64

In [13]:
pd.get_dummies(df['Employment']).head(10)

,"Employed, full-time","Employed, full-time;Employed, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed","Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time;Retired","Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work","Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed;Retired","Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time",...,"Student, full-time;Not employed, but looking for work;Not employed, and not looking for work;Student, part-time","Student, full-time;Not employed, but looking for work;Retired","Student, full-time;Not employed, but looking for work;Student, part-time","Student, full-time;Retired","Student, full-time;Student, part-time","Student, full-time;Student, part-time;Employed, part-time","Student, full-time;Student, part-time;Retired","Student, part-time","Student, part-time;Employed, part-time","Student, part-time;Retired"
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [17]:
missing_values = df.isnull().sum().sort_values(ascending=False).head(20)
print(f"The number of missing values: {missing_values}")

The number of missing values: AINextMuch less integrated       64289
AINextLess integrated            63082
AINextNo change                  52939
AINextMuch more integrated       51999
EmbeddedAdmired                  48704
EmbeddedWantToWorkWith           47837
EmbeddedHaveWorkedWith           43223
ConvertedCompYearly              42002
AIToolNot interested in Using    41023
AINextMore integrated            41009
Knowledge_9                      37802
Frequency_3                      37727
Knowledge_8                      37679
ProfessionalTech                 37673
Knowledge_7                      37659
Knowledge_6                      37573
Knowledge_5                      37557
Knowledge_2                      37416
Knowledge_4                      37407
Knowledge_3                      37342
dtype: int64

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [19]:
ConvertedCompYearly_missingvalue = df['ConvertedCompYearly'].sum()
print(f"In the ConvertedCompYearly Column, the number of missing values is: {ConvertedCompYearly_missingvalue}")

In the ConvertedCompYearly Column, the number of missing values is: 2019049157.0

In [22]:
df['ConvertedCompYearly'] = df['ConvertedCompYearly'].fillna(df['ConvertedCompYearly'].median())

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [23]:
df['RemoteWork'] = df['RemoteWork'].fillna(df['RemoteWork'].mode()[0])

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [25]:
min_value = (df['ConvertedCompYearly'] - df['ConvertedCompYearly'].min())
max_value = (df['ConvertedCompYearly'].max()) - (df['ConvertedCompYearly'].min())

df['ConvertedCompYearly_MinMax_Value'] = (min_value) / (max_value)

df['ConvertedCompYearly_MinMax_Value'].head(10)

0    0.003998
1    0.003998
2    0.003998
3    0.003998
4    0.003998
5    0.003998
6    0.003998
7    0.003998
8    0.003998
9    0.003998
Name: ConvertedCompYearly_MinMax_Value, dtype: float64

In [26]:
df[['ConvertedCompYearly', 'ConvertedCompYearly_MinMax_Value']].head(10)

   ConvertedCompYearly  ConvertedCompYearly_MinMax_Value
0              65000.0                          0.003998
1              65000.0                          0.003998
2              65000.0                          0.003998
3              65000.0                          0.003998
4              65000.0                          0.003998
5              65000.0                          0.003998
6              65000.0                          0.003998
7              65000.0                          0.003998
8              65000.0                          0.003998
9              65000.0                          0.003998

In [27]:
df['ConvertedCompYearly_MinMax_Value'].describe()

count    65437.000000
mean         0.004464
std          0.006903
min          0.000000
25%          0.003998
50%          0.003998
75%          0.003998
max          1.000000
Name: ConvertedCompYearly_MinMax_Value, dtype: float64

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [28]:
import numpy as np

In [29]:
df['ConvertedCompYearly_Log'] = np.log(df['ConvertedCompYearly'])

In [30]:
df[['ConvertedCompYearly', 'ConvertedCompYearly_Log']].head(10)

   ConvertedCompYearly  ConvertedCompYearly_Log
0              65000.0                11.082143
1              65000.0                11.082143
2              65000.0                11.082143
3              65000.0                11.082143
4              65000.0                11.082143
5              65000.0                11.082143
6              65000.0                11.082143
7              65000.0                11.082143
8              65000.0                11.082143
9              65000.0                11.082143

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [31]:
df['YearsCodePro'].describe()

count     51610
unique       52
top           2
freq       4168
Name: YearsCodePro, dtype: object

In [33]:
df['YearsCodePro'].value_counts(ascending=True)

YearsCodePro
47                      10
49                      11
48                      14
50                      14
46                      21
43                      37
44                      42
More than 50 years      50
41                      51
39                      54
42                      55
45                      56
37                     104
31                     106
36                     119
33                     132
38                     134
34                     169
32                     194
40                     194
29                     196
35                     285
28                     342
27                     380
21                     380
26                     426
23                     448
22                     492
19                     516
24                     632
30                     689
17                     814
18                     867
16                     946
25                     998
14                    1082
13                    1127
11                    1312
9                     1493
20                    1549
15                    1635
12                    1777
7                     2517
8                     2549
1                     2639
6                     2843
Less than 1 year      2856
4                     3215
10                    3251
5                     3526
3                     4093
2                     4168
Name: count, dtype: int64

In [34]:
missing_years_value = df['YearsCodePro'].isnull().sum()
print(f"The number of missing values in YearsCodePro : {missing_years_value}")

The number of missing values in YearsCodePro : 13827

In [35]:
df['YearsCodePro'] = pd.to_numeric(df['YearsCodePro'], errors='coerce')

In [36]:
df['ExperienceLevel'] = pd.cut(
    df['YearsCodePro'],
    bins=[0,5,10,100], 
    labels=['Junior', 'Mid-level', 'Senior']
)

In [37]:
df['ExperienceLevel'].value_counts()

ExperienceLevel
Senior       18410
Junior       17641
Mid-level    12653
Name: count, dtype: int64

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.